language: android
android:
  components:
    - build-tools-28.0.3
    - android-28

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-3/modules-3.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
